version: '3.8'

services:
  platform_frontend:
    container_name: platform_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: platform-frontend:1.0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ../frontend:/platform_frontend
    networks:
      - app-network

  platform_backend:
    container_name: platform_backend
    environment:
            TZ: "America/Sao_Paulo"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/:/platform_backend
    image: platform-backend:1.0
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
    depends_on:
      - platform_postgres
      - platform_redis
    networks:
      - app-network

  platform_postgres:
    container_name: platform_postgres
    image: postgres:15.1
    restart: always
    ports:
      - "9022:5432"
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ./database/:/database   
      - ./postgres/data:/var/lib/postgresql/data   
    networks:
      - app-network
      
  platform_redis:
    container_name: platform_redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
